/*
 * mcspi_interface_def.h
 *
 *  Created on: Nov 19, 2016
 *      Author: John Smith
 */

#ifndef STM32F4XX_INTERFACE_MCSPI_INTERFACE_DEF_H_
#define STM32F4XX_INTERFACE_MCSPI_INTERFACE_DEF_H_

#define SPI_INTERFACE_COUNT					6
#define SPI_CHANNELS_PER_INTERFACE_COUNT	4

#endif /* STM32F4XX_INTERFACE_MCSPI_INTERFACE_DEF_H_ */
