/*
 * interface/mmcsd_def.h
 */

#ifndef AM33_INTERFACE_HS_MMCSD_INTERFACE_DEF_H_
#define AM33_INTERFACE_HS_MMCSD_INTERFACE_DEF_H_

#define MMCSD_INTERFACE_COUNT	1

#define MMC_SD_INTERFACE(INTERFACE_NR)	&uSdCardInfo

#define MMCSD_NULL_TRANSFERR_TO_INTERFACE_PTR	true

#endif /* AM33_INTERFACE_HS_MMCSD_INTERFACE_DEF_H_ */
