/*
 * uart_interface_def.h
 *
 *  Created on: Nov 20, 2016
 *      Author: John Smith
 */

#ifndef STM32F4XX_INTERFACE_UART_INTERFACE_DEF_H_
#define STM32F4XX_INTERFACE_UART_INTERFACE_DEF_H_

#define UART_HAVE_MODE_SYNCHRONOUS			0
#define UART_HAVE_MODE_SPI					0
#define UART_HAVE_MODE_IR					0

#define UART_HAVE_STOP_BITS_ONE_AND_HALF	0

#define UART_HAVE_WORD_LEN_5BITS			0
#define UART_HAVE_WORD_LEN_6BITS			0
#define UART_HAVE_WORD_LEN_7BITS			1
#define UART_HAVE_WORD_LEN_9BITS			1

#define UART_INTERFACE_COUNT				8

#endif /* STM32F4XX_INTERFACE_UART_INTERFACE_DEF_H_ */
